# Generated by Django 4.2 on 2023-07-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Father_name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('College', models.TextField()),
                ('Course', models.TextField()),
                ('Degree', models.CharField(max_length=150)),
                ('NEW', models.BooleanField(blank=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course1', models.CharField(max_length=100)),
            ],
        ),
    ]
