# Generated by Django 4.2 on 2023-07-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name1', models.CharField(max_length=100)),
                ('Father_name1', models.CharField(max_length=100)),
                ('Age1', models.IntegerField()),
                ('Date_of_birth1', models.DateField()),
                ('address1', models.TextField()),
                ('College1', models.TextField()),
                ('Course1', models.TextField()),
                ('Degree1', models.CharField(max_length=150)),
                ('Email1', models.EmailField(max_length=254)),
                ('Mobile_number1', models.IntegerField()),
            ],
        ),
    ]
