# Generated by Django 4.2 on 2023-07-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0003_alter_student1_mobile_number1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='Mobile_number1',
            field=models.IntegerField(null=True),
        ),
    ]
