# Generated by Django 4.2 on 2023-07-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0005_question1_question2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question1',
        ),
    ]
