# Generated by Django 4.2 on 2023-07-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0007_question3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Que1', models.TextField()),
                ('Que2', models.TextField()),
                ('Que3', models.TextField()),
                ('Que4', models.TextField()),
                ('Que5', models.TextField()),
                ('Que6', models.TextField()),
                ('Que7', models.TextField()),
                ('Que8', models.TextField()),
                ('Que9', models.TextField()),
                ('Que10', models.TextField()),
            ],
        ),
    ]
